from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class WeaponDefinition:
    id: str
    name: str
    slot: str
    range_px: int
    damage: int
    cooldown: float
    asset_hint: str
    price: int
    rarity: str
    category: str
    icon_hint: str
    animation_key: str
    online_sync: bool = True
    bullet_speed: float = 720.0
    spread_degrees: float = 2.0
    armor_piercing: int = 8
    recoil_shake: float = 0.0

    @property
    def range(self) -> int:
        return self.range_px

    @property
    def shots_per_second(self) -> float:
        return 0.0 if self.cooldown <= 0 else round(1.0 / self.cooldown, 2)


WEAPONS: dict[str, WeaponDefinition] = {
    "rifle": WeaponDefinition(
        "rifle",
        "Rifle",
        "primary",
        430,
        32,
        0.18,
        "allied_soldier fire/rifle",
        0,
        "common",
        "assault_rifle",
        "rifle",
        "rifle",
        bullet_speed=720,
        spread_degrees=2.2,
        armor_piercing=8,
        recoil_shake=0.02,
    ),
    "ak47": WeaponDefinition(
        "ak47",
        "AK-47",
        "primary",
        440,
        38,
        0.2,
        "tn_imported/ak47",
        850,
        "uncommon",
        "assault_rifle",
        "ak47",
        "rifle",
        bullet_speed=735,
        spread_degrees=4.2,
        armor_piercing=10,
        recoil_shake=0.035,
    ),
    "ak74": WeaponDefinition(
        "ak74",
        "AK-74",
        "primary",
        470,
        34,
        0.16,
        "tn_imported/ak74",
        1050,
        "rare",
        "assault_rifle",
        "ak74",
        "rifle",
        bullet_speed=780,
        spread_degrees=2.7,
        armor_piercing=9,
        recoil_shake=0.025,
    ),
    "stv_380": WeaponDefinition(
        "stv_380",
        "STV-380",
        "primary",
        455,
        36,
        0.18,
        "tn_imported/stv_380",
        980,
        "uncommon",
        "assault_rifle",
        "stv_380",
        "rifle",
        bullet_speed=800,
        spread_degrees=2.0,
        armor_piercing=11,
        recoil_shake=0.025,
    ),
    "svd": WeaponDefinition(
        "svd",
        "SVD",
        "primary",
        760,
        82,
        0.95,
        "tn_imported/svd",
        1650,
        "epic",
        "marksman_rifle",
        "svd",
        "sniper",
        bullet_speed=980,
        spread_degrees=0.6,
        armor_piercing=28,
        recoil_shake=0.08,
    ),
    "mosin": WeaponDefinition(
        "mosin",
        "Mosin",
        "primary",
        820,
        96,
        1.3,
        "tn_imported/mosin",
        1450,
        "rare",
        "bolt_action",
        "mosin",
        "sniper",
        bullet_speed=1020,
        spread_degrees=0.45,
        armor_piercing=32,
        recoil_shake=0.1,
    ),
    "vss": WeaponDefinition(
        "vss",
        "VSS",
        "primary",
        610,
        46,
        0.28,
        "tn_imported/vss",
        1550,
        "epic",
        "suppressed_rifle",
        "vss",
        "sniper",
        bullet_speed=680,
        spread_degrees=1.1,
        armor_piercing=20,
        recoil_shake=0.025,
    ),
    "tokarev": WeaponDefinition(
        "tokarev",
        "Tokarev",
        "sidearm",
        330,
        28,
        0.24,
        "tn_imported/tokarev",
        390,
        "common",
        "pistol",
        "tokarev",
        "pistol",
        bullet_speed=620,
        spread_degrees=5.0,
        armor_piercing=5,
        recoil_shake=0.02,
    ),
    "makarov": WeaponDefinition(
        "makarov",
        "Makarov",
        "sidearm",
        300,
        24,
        0.22,
        "tn_imported/makarov",
        320,
        "common",
        "pistol",
        "makarov",
        "pistol",
        bullet_speed=560,
        spread_degrees=4.3,
        armor_piercing=4,
        recoil_shake=0.015,
    ),
    "gun_bash": WeaponDefinition(
        "gun_bash",
        "Gun Bash",
        "melee",
        58,
        34,
        0.38,
        "rifle stock melee",
        0,
        "common",
        "melee",
        "rifle",
        "melee_bash",
    ),
    "pickaxe": WeaponDefinition(
        "pickaxe",
        "Pickaxe",
        "melee",
        62,
        46,
        0.34,
        "prop_030/031",
        120,
        "common",
        "tool",
        "pickaxe",
        "melee_swing",
    ),
    "grenade": WeaponDefinition(
        "grenade",
        "Grenade",
        "throwable",
        980,
        120,
        0.75,
        "prop_112-117",
        220,
        "uncommon",
        "explosive",
        "grenade",
        "grenade_throw",
    ),
    "medkit": WeaponDefinition(
        "medkit",
        "Medkit",
        "support",
        0,
        -55,
        1.0,
        "tn_imported/medkit",
        180,
        "common",
        "medical",
        "medkit",
        "support_use",
        online_sync=False,
    ),
    "ammo_support": WeaponDefinition(
        "ammo_support",
        "Ammo Support",
        "support",
        0,
        0,
        1.0,
        "tn_imported/ammo_support",
        160,
        "common",
        "supply",
        "ammo_crate",
        "support_use",
        online_sync=False,
    ),
    "mortar": WeaponDefinition(
        "mortar",
        "Mortar",
        "support",
        1200,
        130,
        8.0,
        "prop_098-102",
        1250,
        "rare",
        "artillery",
        "mortar",
        "mortar_fire",
    ),
    "tank_cannon": WeaponDefinition(
        "tank_cannon",
        "Tank Cannon",
        "vehicle",
        560,
        58,
        1.1,
        "m4_sherman fire",
        2100,
        "epic",
        "vehicle_weapon",
        "tank_cannon",
        "tank_cannon_fire",
    ),
}


def weapon_name(weapon_id: str) -> str:
    return WEAPONS.get(weapon_id, WEAPONS["rifle"]).name


__all__ = ["WEAPONS", "WeaponDefinition", "weapon_name"]
