MAPS = {
    "jungle_outpost": {
        "title": "Forward Safehouse",
        "briefing": "Gear up inside the secured perimeter, then breach the jungle outpost.",
        "rows": [
            "############################",
            "#..SSSSSSS..t....rrrr...w..#",
            "#..S.....S..t....r..r...w..#",
            "#..S..M..S.ttt...r..r...w..#",
            "#..S..A..Srrrr...r..rrrrw..#",
            "#..S.....S.......r.........#",
            "#..SSSDSSS..####.r..####...#",
            "#....r......####....####...#",
            "#....r......####....####...#",
            "#..rrrrrr...####....####...#",
            "#..r.......................#",
            "#..r..tttt....rrrrrrrr.....#",
            "#..r....t.....r............#",
            "#..r.####.....r....####....#",
            "#..r.####...ttt....####....#",
            "#..r.####.....r....####....#",
            "#..r..........rrrr.........#",
            "#..r..www....r.C.r..ggg....#",
            "#.....www....rrrrr..ggg....#",
            "#..........................#",
            "############################",
        ],
        "spawns": {
            "player": (5, 4),
            "enemies": [(20, 3), (22, 10), (17, 14), (12, 10), (10, 18)],
            "tanks": [(23, 16), (6, 12)],
        },
        "items": {
            "medkit": [(5, 3), (8, 19)],
            "grenade": [(6, 4), (14, 11)],
            "ammo": [(4, 5), (11, 9)],
        },
        "safe_zones": [
            {"name": "forward_safehouse", "rect": (3, 1, 7, 6)},
        ],
        "doors": [(6, 6)],
    },
    "trench_line": {
        "title": "Trench Line",
        "briefing": "Push through the trench network before taking the bunker.",
        "rows": [
            "############################",
            "#........rrrrrr............#",
            "#..tttt..r....r..tttttt....#",
            "#..t..t..r....r..t....t....#",
            "#..t..t..rrrrrr..t....t....#",
            "#..t..t..........t....t....#",
            "#..t..tttttttttttt....t....#",
            "#..t..................t....#",
            "#..tttttt..####..tttttt....#",
            "#..........#..#............#",
            "#..rrrrrr...CC...rrrrrr....#",
            "#..r.......####.......r....#",
            "#..r..wwww......wwww..r....#",
            "#..r..wwww......wwww..r....#",
            "#..rrrrrr..tttt..rrrrrr....#",
            "#..........................#",
            "#..gggg............gggg....#",
            "#..gggg....tttt....gggg....#",
            "#..........................#",
            "#............rrrr..........#",
            "############################",
        ],
        "spawns": {
            "player": (3, 18),
            "enemies": [(18, 3), (21, 5), (18, 16), (7, 7), (12, 15), (23, 18)],
            "tanks": [(20, 10), (10, 3)],
        },
        "items": {
            "medkit": [(5, 18), (15, 15)],
            "grenade": [(8, 7), (20, 17)],
            "ammo": [(11, 18), (16, 2)],
        },
    },
    "river_bridge": {
        "title": "River Bridge",
        "briefing": "Cross the bridge, destroy armor, and secure the far side.",
        "rows": [
            "############################",
            "#.....ggg............ggg...#",
            "#.....ggg....tttt....ggg...#",
            "#............t..t..........#",
            "#..rrrrrrrrrrt..trrrrrrr...#",
            "#..r...................r...#",
            "#..r..wwwwwwwwwwwwww...r...#",
            "#..r..wwwwwwwwwwwwww...r...#",
            "#..rrrrrrrrrrrrrrrrrrrrr...#",
            "#.....wwwwwwwwwwwwww.......#",
            "#.....wwwwwwwwwwwwww.......#",
            "#..rrrrrrrrrrrrrrrrrrrrr...#",
            "#..r...................r...#",
            "#..r...####......####..r...#",
            "#..r...####..CC..####..r...#",
            "#..r...####......####..r...#",
            "#..rrrrrrrr..tt..rrrrrrr...#",
            "#............tt............#",
            "#..ggg................ggg..#",
            "#..........................#",
            "############################",
        ],
        "spawns": {
            "player": (3, 19),
            "enemies": [(21, 3), (22, 12), (16, 15), (12, 4), (7, 16)],
            "tanks": [(22, 14), (10, 8), (17, 8)],
        },
        "items": {
            "medkit": [(5, 18), (20, 12)],
            "grenade": [(9, 16), (16, 13)],
            "ammo": [(6, 5), (23, 3)],
        },
    },
    "armored_front": {
        "title": "Armored Front",
        "briefing": "Advance from the rear safe zone, break the armored roadblock, and seize the rail depot.",
        "rows": [
            "##########################################",
            "#..SSSSSSSSS....ggg.....rrrrrr.....wwwww.#",
            "#..S.......S....ggg.....r....r.....wwwww.#",
            "#..S..M.A..S............r.tt.r...........#",
            "#..S.......S..rrrrrrrrrrrrtt.rrrrrrrr....#",
            "#..SSSDDSSSS..r.......ttt....t.....r.....#",
            "#......r......r..####..t..####....r......#",
            "#......r..ttt.r..####.....####....r.gg...#",
            "#..rrrrrrrrr..r..####..C..####..rrrrgg...#",
            "#..r......t...r..####.....####..r........#",
            "#..r..www.t...rrrrrrrrrrrrrrrrrrr..ttt...#",
            "#..r..www.t.........wwwwww.......r..t....#",
            "#..r..wwwwwww.......wwwwww.......r..t....#",
            "#..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..t....#",
            "#...........t..####....tt....####........#",
            "#..gggg.....t..####....tt....####..ggg...#",
            "#..gggg..rrrr..####..rrrrrr..####..ggg...#",
            "#........r..r........r....r..............#",
            "#..tttt..r..rrrrrrrrrr....rrrrrr..ttt....#",
            "#..t.....r.......tt.........t..r..t......#",
            "#..t.....rrrrrr..tt..rrrrrrrr..r..t......#",
            "#..tttt.........wwwwww.........r..ttt....#",
            "#........rrrrrrrwwwwwwrrrrrrrrrr.........#",
            "#..ggg...r....................r...ggg....#",
            "#........rrrrrrrrrrrrrrrrrrrrrr..........#",
            "##########################################",
        ],
        "spawns": {
            "player": (6, 4),
            "enemies": [(25, 3), (31, 7), (20, 10), (33, 12), (16, 17), (27, 18), (35, 20), (12, 23)],
            "tanks": [(30, 4), (23, 13), (34, 16), (15, 20), (24, 23)],
            "aircraft_enemies": [
                {
                    "id": "bomber_north_run",
                    "unit": "bomber",
                    "entry": (8, -2),
                    "exit": (35, 27),
                    "target": (23, 8),
                    "delay": 18.0,
                    "cooldown": 42.0,
                },
                {
                    "id": "bomber_river_run",
                    "unit": "bomber",
                    "entry": (43, 6),
                    "exit": (-3, 21),
                    "target": (25, 13),
                    "delay": 34.0,
                    "cooldown": 55.0,
                },
            ],
        },
        "safe_zones": [
            {"name": "western_depot", "rect": (2, 1, 11, 6)},
        ],
        "doors": [(6, 5), (7, 5)],
        "capture_points": [
            {"id": "rail_depot", "tile": (24, 8), "radius": 2},
        ],
        "items": {
            "medkit": [(5, 3), (9, 22), (17, 17), (34, 23)],
            "grenade": [(7, 4), (14, 9), (29, 17), (36, 17)],
            "ammo": [(8, 3), (12, 13), (21, 20), (31, 6), (37, 24)],
        },
        "boss_wave": {
            "trigger_radius_tile": (24, 8),
            "boss_spawn": (36, 8),
            "boss_kind": "super_heavy",
            "adds_spawns": [(34, 4), (34, 12), (37, 10), (37, 6)],
        },
    },


    "pvp_solo_arena": {
        "title": "PVP Solo Arena",
        "briefing": "Đấu trường riêng cho PVP solo: nhiều lớp cover, góc bắn tỉa và hành lang áp sát.",
        "rows": [
            "##########################################",
            "#........................................#",
            "#.ggg..............wwww..............ggg.#",
            "#.ggg..###.........wwDw.........###..ggg.#",
            "#.ggg..###.........wwww.........###..ggg.#",
            "#.ggg..###........rrrrrr........###..ggg.#",
            "#......###.........wwww.........###......#",
            "#..................wwww..................#",
            "#...tttttttttttt...wwww...tttttttttttt...#",
            "#..................wwww..................#",
            "#..................wwww..................#",
            "#..................wwww..................#",
            "#.................rrrCrr.................#",
            "#..................wwww..................#",
            "#..................wwww..................#",
            "#..................wwww..................#",
            "#...tttttttttttt...wwww...tttttttttttt...#",
            "#..................wwww..................#",
            "#..................wwww..................#",
            "#.................rrrrrr.................#",
            "#..........###.....wwww.....###..........#",
            "#.SSSSSSS..###.....wwww.....###..........#",
            "#.SSSMSSS..###.....wwww.....###.....A....#",
            "#.SSSSSSS..........wwww..................#",
            "#........................................#",
            "##########################################",
        ],
        "spawns": {
            "player": (10, 22),
            "enemies": [(35, 6), (31, 12), (33, 20)],
            "tanks": [],
        },
        "items": {
            "medkit": [(9, 22), (35, 6)],
            "grenade": [(14, 10), (28, 14)],
            "ammo": [(10, 22), (30, 6)],
        },
        "safe_zones": [{"name": "solo_spawn_pocket", "rect": (2, 21, 7, 3)}],
    },


    "jungle_outpost_mega": {
        "title": 'MEGA: Tiền Đồn Rừng Sâu',
        "briefing": 'Khu rừng khổng lồ (112x84). Nhiều đường mòn rẽ nhánh và các lùm cây dày đặc. Căn cứ đã được quy hoạch lại với 1 trạm đạn/máu.',
        "rows": [
            "################################################################################################################",
            "######.........##########............#############..............############.....#############.....#...........#",
            "######..........#########............#############..............############.....#############...#####.........#",
            "########........#########...........###############...............###########....#############..#######........#",
            "##########......##########..........###############..............#############..###############.#######........#",
            "############...############.........###############..............#############..#######################........#",
            "############..#############..#.....################.....#........##############.###############.#######........#",
            "############.####################...###############.rrrrrrrrr...###############################.#######..#.....#",
            "##################################..################rrrrrrrrr#...##############.###############..#####.#####...#",
            "###################################.################rrrrrrrrr##..##############.###############........#####...#",
            "####################################.###############rrrrrrrrr##.###############.###############.......######...#",
            "####################################.###############rrrrrrrrr##################..#############.........#####...#",
            "####################################..##############rrrrrrrrr##################..#############....#....#####...#",
            "####################################....############rrrrrrrrr####################.###########...#####..#.......#",
            "####################################.....#.#########rrrrrrrrr##############################.....###########....#",
            "####################################..##############rrrrrrrrr########################..#######.#############...#",
            "####################################.###############rrrrrrrrr##################################.#############..#",
            "#######rrrrrrrr####################.################rrrrrrrrr####################################rrrrrrrr####..#",
            "#######rrrrrrrrrr#################..################rrrrrrrrr##################################rrrrrrrrrr####..#",
            "#######rrrrrrrrrrrr##############...################rrrrrrrrr################################rrrrrrrrrrrr####..#",
            "#######rrrrrrrrrrrrrrr#.##########.#################rrrrrrrrr#...#########################rrrrrrrrrrrrrrr####..#",
            "#######rrrrrrrrrrrrrrrrr###########.################rrrrrrrrr##...######################rrrrrrrrrrrrrrrrr#######",
            "#######rrrrrrrrrrrrrrrrrr##########.################rrrrrrrrr##...#####################rrrrrrrrrrrrrrrrrr#######",
            "#######rrrrrrrrrrrrrrrrrrrr########.################rrrrrrrrr##...###################rrrrrrrrrrrrrrrrrrrr#######",
            "#######..rrrrrrrrrrrrrrrrrrrrr#####..###############rrrrrrrrr##.##################rrrrrrrrrrrrrrrrrrrrr#########",
            "#....#.####rrrrrrrrrrrrrrrrrrrrr###...#######.......rrrrrrrrr###################rrrrrrrrrrrrrrrrrrrrr.##########",
            "#.###########rrrrrrrrrrrrrrrrrrrrr##................rrrrrrrrr#################rrrrrrrrrrrrrrrrrrrrr...##########",
            "################rrrrrrrrrrrrrrrrrrrr#........#......rrrrrrrrr.##############rrrrrrrrrrrrrrrrrrrr###..###########",
            "##################rrrrrrrrrrrrrrrrrrrr.....#####....rrrrrrrrr#############rrrrrrrrrrrrrrrrrrrr#####...##########",
            "###################rrrrrrrrrrrrrrrrrrrrr...#####....rrrrrrrrr###########rrrrrrrrrrrrrrrrrrrrr######...##########",
            "####################.rrrrrrrrrrrrrrrrrrrrr######....rrrrrrrrr#########rrrrrrrrrrrrrrrrrrrrr#.#####....##########",
            "########################rrrrrrrrrrrrrrrrrrrrr###....rrrrrrrrr######rrrrrrrrrrrrrrrrrrrrr###########....#########",
            "##########################rrrrrrrrrrrrrrrrrrrrr#...#rrrrrrrrr####rrrrrrrrrrrrrrrrrrrrr#############.....########",
            "############################rrrrrrrrrrrrrrrrrrrr....rrrrrrrrr###rrrrrrrrrrrrrrrrrrrr###############......#######",
            "#########################.####rrrrrrrrrrrrrrrrrrrr.#rrrrrrrrr#rrrrrrrrrrrrrrrrrrrrr################............#",
            "##############.#########..######rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr###################............#",
            "#.############..#######....#######rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#####################.#.......####",
            "#..###########.............#########rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr###########################..#######",
            "#...##########..........############.##rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#######################################",
            "#........#####........###########....####rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#########################################",
            "#....................#############...#####rrrrrrrrrrrrrrrrrrrrrrrrrrrr###########################.####.#########",
            "#........#........################..########rrrrrrrrrrrrrrrrrrrrrrrr###########################...##############",
            "#......#####.....##################..########rrrrrrrrrrrrrrrrrrrrrr######################.........##############",
            "#......#####....###################..######rrrrrrrrrrrrrrrrrrrrrrrrrr##################......#.....#############",
            "#.....######....###################..#####rrrrrrrrrrrrrrrrrrrrrrrrrrrr##########..........#######..#############",
            "#......#####....###################...###rrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#########.........#########..############",
            "#......#####...####################....rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#######........###########.....########",
            "#.....#.........###################...rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr######.......#############.....#######",
            "#..#######......###################.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr####.......#############.....#######",
            "#.#########.....##################.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##........#############......######",
            "############.....################rrrrrrrrrrrrrrrrrrrrrr##rrrrrrrrrrrrrrrrrrrrrr.......##############........####",
            "#############.....##############rrrrrrrrrrrrrrrrrrrrr..####rrrrrrrrrrrrrrrrrrrrr.......#############...........#",
            "#############...........######rrrrrrrrrrrrrrrrrrrrr....######rrrrrrrrrrrrrrrrrrrrr.....#############...........#",
            "#############.........#######rrrrrrrrrrrrrrrrrrrrr......######rrrrrrrrrrrrrrrrrrrrr....#############...........#",
            "#############........#######rrrrrrrrrrrrrrrrrrrrr........######rrrrrrrrrrrrrrrrrrrrr...############.........####",
            "#############........#####rrrrrrrrrrrrrrrrrrrrr...........#######rrrrrrrrrrrrrrrrrrrrr############.........#####",
            "#############........###rrrrrrrrrrrrrrrrrrrrrr...............#####rrrrrrrrrrrrrrrrrrrrrr##########........######",
            "#############.....######rrrrrrrrrrrrrrrrrrrr..................######rrrrrrrrrrrrrrrrrrrr##########...#...#######",
            "############.....#####rrrrrrrrrrrrrrrrrrrrr..................########rrrrrrrrrrrrrrrrrrrrr########.#####.#######",
            "###########.....####rrrrrrrrrrrrrrrrrrrrrr#..................#########rrrrrrrrrrrrrrrrrrrrrr####################",
            "##########....#####rrrrrrrrrrrrrrrrrrrrr###..................###########rrrrrrrrrrrrrrrrrrrrr###################",
            "#.#####....#######rrrrrrrrrrrrrrrrrrrr#####.................##############rrrrrrrrrrrrrrrrrrrr##################",
            "#.........######rrrrrrrrrrrrrrrrrrrrrr......................###############rrrrrrrrrrrrrrrrrrrrr..##############",
            "#........######rrrrrrrrrrrrrrrrrrrrr........................################rrrrrrrrrrrrrrrrrrrrr.##############",
            "#.#......####rrrrrrrrrrrrrrrrrrrrr.....#...................#################..rrrrrrrrrrrrrrrrrrrrr#####..######",
            "######...###rrrrrrrrrrrrrrrrrrrrr....#####..................###############....rrrrrrrrrrrrrrrrrrrrr.......#####",
            "#######.##rrrrrrrrrrrrrrrrrrrrrr#....######.................###############.....rrrrrrrrrrrrrrrrrrrrrr......####",
            "########.rrrrrrrrrrrrrrrrrrrrr####..#########................##############.......rrrrrrrrrrrrrrrrrrrrr........#",
            "#######rrrrrrrrrrrrrrrrrrrrr#######..#########...................##########.........rrrrrrrrrrrrrrrrrrrrr......#",
            "######rrrrrrrrrrrrrrrrrrrrr########..#########SSSSSSSSDDDDSSSSSSSS.#######...........rrrrrrrrrrrrrrrrrrrrr.....#",
            "######rrrrrrrrrrrrrrrrrrrr#########.....######S..................S.............#......rrrrrrrrrrrrrrrrrrrrr....#",
            "######rrrrrrrrrrrrrrrrrr###########.....######S..................S..........#######.....rrrrrrrrrrrrrrrrrrr....#",
            "######rrrrrrrrrrrrrrrrr############......#####S..................S.........#########.....rrrrrrrrrrrrrrrrrr....#",
            "######rrrrrrrrrrrrrrr##############.......####S..................S........###########...###rrrrrrrrrrrrrrrr....#",
            "######rrrrrrrrrrrrrr###############.......####S....M........A....S........############.#####rrrrrrrrrrrrrrr##..#",
            "######rrrrrrrrrrrrr###############.........###S..................S........###################rrrrrrrrrrrrrr###.#",
            "######rrrrrrrrrrr################.#...........S..................S......#######################rrrrrrrrrrrr###.#",
            "######rrrrrrrrr####.#################.........S..................S.....##########################rrrrrrrrrr#####",
            "#..###rrrrrrrrr####...###############.........SSSSSSSSSSSSSSSSSSSS....############################rrrrrrrrr#####",
            "#.#################...###############......................#######.#..##########################################",
            "#..################...###############......................#####################################################",
            "#..################..################.....................######################################################",
            "#..###############....###########..........................#####################################################",
            "################################################################################################################",
        ],
        "spawns": {'player': (56, 74), 'enemies': [(20, 20), (29, 24), (52, 12), (52, 10), (56, 12), (63, 10), (64, 9), (82, 24), (93, 19), (18, 24), (30, 25), (45, 25), (56, 24), (68, 31), (84, 24), (94, 24), (24, 31), (36, 38), (48, 40), (64, 40), (75, 37), (87, 31), (56, 46)], 'tanks': [(23, 21), (40, 26), (56, 16), (60, 16), (88, 21), (34, 34), (78, 34), (56, 42)]},
        "safe_zones": [{'rect': (46, 69, 20, 10)}],
    },
    "trench_line_mega": {
        "title": 'MEGA: Trận Địa Chiến Hào',
        "briefing": 'Gấp 16 lần diện tích cũ. Rất nhiều chiến hào và bong-ke kiên cố. Cẩn thận các ổ phục kích trong hố bom.',
        "rows": [
            "################################################################################################################",
            "#.rrrrrrr.....................................rrrrrrrr..rrrrrrrrrrr............................................#",
            "#.rrrrrrr.....................................rrrrrrrrrrrrrrrrrrrrr....................................r.......#",
            "#rrrrrrrr......r..............................rrrrrrrrrrrrrrrrrrrrr..................................rrrrr.....#",
            "#.rrrrrrr....rrrrr..........r.................rrrrrrrrrrrrrrrrrrrrr.................................rrrrrrr....#",
            "#.rrrrrrr...rrrrrrrr.......rrr...............rrrrrrrrrrrrrrrrrrrrrr.................................rrrrrrr....#",
            "#..rrrrr....rrrrrrrrr.....rrrr................rrrrrrrrrrrrrrrrrrrr......r..........................rrrrrrrr....#",
            "#..........rrrrrrrrrr......rrr................rrrrrrrrrrrrrrrrrrr.....rrrrr.........................rrrrrrr....#",
            "#...........rrrrrrrrr.........................rrrrrrrrrrrrrrrrrrr.....rrrrr.....r...................rrrrrrr....#",
            "#...........rrrrrrr............................rrrrrrrrrrrrrrrrrr....rrrrrr...rrrrr..................rrrrr.....#",
            "#............rrrrr..............................r....rrrrrrrrrrrr.....rrrrr...rrrrr...r...........r............#",
            "#..........rrrrr....................r..........rrr..rrrrrrrrrrrrr.....rrrrr..rrrrrr.rrrrr.......rrrrr..........#",
            "#.........rr#######.............r.rrrrr.......rrrr...rrrrrrrrrrr..............rrrrr.rrrrr......rrrrrrr.........#",
            "#.........rr#.....#..........rrrrrrrrrrr.......rrr...rrrrrrrrrr.......r.......rrrr#######......rrrrrrr.........#",
            "#........rrr#.....#r........rrrrrrrrrrrr.....#######.rrrrrrrrr.......rrr..........#.....#.....rrrrrrrr......r..#",
            "#.........rr#.....#r.......rrrrrrrrrrrrr..####.....#..rrrrrrr.......rrrr..........#.....#......ttttttt...rrrrrr#",
            "#.........rr#.....#r.......rrrrrrrrrrrrr..#..#.....#r................rrr..........#.....#rr...rt#######trrrrrrr#",
            "#..........r#.....#........rrrrrrrrrrrrr..#..#.....#rr...........................r#.....#rrrrrtt#.....#ttttrrrr#",
            "#...........#######.......rrrrrrrrrrrrrr..#..#.....#rr........................rrrr#.....#rrrrrtt#.....#ttttttrr#",
            "#.........................#######rrrrrrrr.#..#.....#rr.......................rrrrr#######rrrrttt#.....#tttttttt#",
            "#.........................#.....#rrrrrrttt#..#######rr.......................rrrrrrrrrrrrrrrrttt#.....#tttttttt#",
            "#.........ttttttt.........#.....#rrrrttttt#######rrrrr.......................rrrrrrrrr...rrrtttt#.....#tttttttt#",
            "#.......ttttttttttt.......#.....#rrtttttttttttrrrrrrrr......................rrrrrrrrrr....rrtttt##########ttttt#",
            "#.....ttttttttttttttt.....#.....#rrtttttttttttttrrrrrr.......................rrrrrrrrr....rtttttttr#.....#ttttt#",
            "#...ttttttttttttttttttt...#.....#tttttttttttttttrrrrrr.......................rrrrrrrrr....ttttttttr#.....#.rttt#",
            "#.tttttttttttttttttttttt..#######ttttttttttttttttrrrrr.......................rrrrrrrrr....tttttttr.#.....#.....#",
            "#tttttttttttttttttttttttt.....ttttttttttttttttttttrrrr.............tttttt.....rrrrrrrr...tttttttt..#.....#.....#",
            "#ttttttttttt...tttttttttttt..tttttttttttrrtttttttttrr............ttttttttt........rrrrrrrttttttt...#.....#..r..#",
            "#ttttttttt.......ttttttttttttttttttttttrrrrttttttttt............ttttttttttt......rrrrrrrttttttt....#######rrrrr#",
            "#ttttttt...........tttttttttttttttttt...rrrrtttttttt...........ttttttttttttt.....rrrrrrrttttttt.......rrrrrrrrr#",
            "#ttttt.............tttttttttttttttt..........tttttttt.........ttttttttttttttt....rrrrrrtttttttr........rrrrrrrr#",
            "#ttt.................tttttttttttttt...........tttttttt......ttttttttttttttttt...rrrrrrrtttttttr.........rrrrrrr#",
            "#tt................#######tttttttr.............tttttttt....tttttttttt.ttttttttt..rrrrrtttttttrr........rrrrrrrr#",
            "#........r.........#.....#tttttrrr.............ttttttttt..tttttttttt..tttttttttt.rrrrttttttttrr.........rrrrrrr#",
            "#.......rrr........#.....#ttttt.................ttttttttttttttttttt.....tttttttt.rrrrttttt#######.......rrrrrrr#",
            "#rr....rrrr........#.....#rr.....................ttttttttttttttttt......ttttttttttrrtttttt#.....#.......rrrrrrr#",
            "#rr.....rrr.......r#.....#rr......................tttttttttttttt.........ttttttttt..tttttt#.....#........rrrrrr#",
            "#rr................#.....#rr......................ttttttttttttt............ttttttttttttttt#.....#...........rrr#",
            "#rr................#######rr..#######...............tttttttttt.......r.....ttttttttttttttt#.....#..............#",
            "#rr................rrrrrrrrr..#.....#ttt............ttttttttt.....rrrrrrr...tttttttttttttr#.....#..............#",
            "#.....r.............rrrrrrrr........#ttttt.r.......rrttttttr.....rrrrrrrrr..rttttt.ttttttr#######..............#",
            "#...rrrrr..........rrrrrrrrr..#.....#tttttttrr.....rrrtttt#######rrrrrrrrrrrrrttttttttttrr#######..............#",
            "#...rrrrr..........rrrrrrrrr..#.....#tttttttttrr...rrrrrrr#.....#rrrrrrrrrr.rrrtttttttttrr#.....#..............#",
            "#..rrrrrr.........rrrrrrrrrr..#.....#tttttttttttrrrrrrrrrr#.....#rrrrrrrrrr.rrrrtttttttrrr#.....#..............#",
            "#...rrrrr..........rrrrrrrr..t#######tttttttttttttrrrrrrrr#.....#rrrrrrrrrr.rrrrrttttttrrr#.....#..............#",
            "#...rrrrr..........rrrrrrr..ttttttttt.ttttttttttttttrrrrrr#.....#rrrrrrrrrr..rrrrrtttttrrr#.....#r.............#",
            "#...r...............rrrrr..ttttttttt....ttttttttttttttrrrr#.....#rrrrrrrrrr...rrr......rrr#.....#rrrrr.........#",
            "#..rrr...................rttttttttt......rttttttttttttt##########rrrrrrrrrr..rrrr.........#######rrrrrrrrttttt.#",
            "#.rrrrr................rrrtttttttt..........ttttttttttt#.....#rrrrrrrrrrrrr...rrrr..........rrrrrrrrrrrrtttttt.#",
            "#..rrrrrr.............rrrtttttttt............rttttttttt#.....#ttrrrrrrrrrrr...rrrr..........rrrrrrrrrrrttttttt.#",
            "#...rrrrr.............rrttttttttt.r............rttttttt#.....#tttttrrrrrrrr....rrr.........rrrrrrrrrrrtttttttt.#",
            "#..rrrrrr............rrtttttttt..rrr..............ttttt#.....#tttttttttrrrr...............rrrrrrrrrrrttttttttt.#",
            "#...rrrrr...........r.rtttttttt.rrrr................ttt#.....#ttttttttttttr...............rrrrrrrrrrttttttttt..#",
            "#tttrrrrr..........rrttttttttt...rrr..................r#######ttttttttttttt..............rrrrrrrrrrttttttttt...#",
            "#ttttt..........r.rrrttttttttt.........r...............rrrrrt#######ttttttttt...r.........rrrrrrrrttttttttt....#",
            "#tttttttt.....rrrrrrtttttttt........rrrrrrr..............r...#.....#tttttttttttrrrr.....r.rrrrrrrtttttttttr....#",
            "#tttttttttt..rrrrrrttttttttt.......rrrrrrrrr...........rrrrr.#.....#ttttttttttttrrr..rrrrrrrrrrrtttttttttr.....#",
            "#ttttttttttttrrrrrttttttttt.......rrrrrrrrrrr..........rrrrr.#.....#rrtttttttttt#######rrrrrrrrtttttttttr......#",
            "#tttttttttttttttrttttttttt........rrrrrrrrrrr.........rrrrrr.#.....#rrrttttttttt#.....#rrrrrrrttttttttt...r....#",
            "#.ttttttttttttttttttttttt.........rrrrrrrrrrr..........rrrrr.#.....#rr...ttttttt#.....#rrrrrrttttttttt..rrrrr..#",
            "#....ttttttttttttttttttt.........rrrrrrrrrrrr..........rrrrr.#######.......ttttt#.....#rrrrrttttttttt...rrrrr..#",
            "#......ttttttttttttttttt..........rrrrrrrrrrr...............................tttt#.....#rrrrttttttttt...rrrrrr..#",
            "#........ttttttttttttt............rrrrrrrrrrr................................ttt#.....#ttrttttttttt.....rrrrr..#",
            "#...........tttttttttt............rrrrrrrrrrr..................................t#######ttttttttttt......rrrrr..#",
            "#.............ttttttt..............rrrrrrrrr.....................................tttttttttttttttt..............#",
            "#...............ttttt...............rrrrrrr.......................................ttttttttttttttr..............#",
            "#..................................................................................ttttttttttttr...............#",
            "#....................................................................................tttttttttr................#",
            "#......................................................................................tttttt..................#",
            "#.......................................................................................ttttt..................#",
            "#..............................................................................................................#",
            "#..............................................................................................................#",
            "#...........................................SSSSSSSSSSDDDDSSSSSSSSSS...........................................#",
            "#...........................................S......................S...........................................#",
            "#...........................................S......................S...........................................#",
            "#...........................................S......................S...........................................#",
            "#...........................................S.....M...........A....S...........................................#",
            "#...........................................S......................S...........................................#",
            "#...........................................S......................S...........................................#",
            "#...........................................SSSSSSSSSSSSSSSSSSSSSSSS...........................................#",
            "#..............................................................................................................#",
            "#..............................................................................................................#",
            "#..............................................................................................................#",
            "#..............................................................................................................#",
        ],
        "spawns": {'player': (56, 76), 'enemies': [(37, 45), (37, 46), (39, 46), (59, 40), (64, 36), (69, 32), (71, 34), (94, 30), (100, 30), (35, 47), (34, 48), (43, 48), (62, 38), (64, 38), (74, 38), (89, 39), (97, 38), (33, 49), (31, 51), (40, 47), (49, 51), (62, 48), (70, 46), (80, 46), (89, 46), (100, 46), (28, 56), (44, 56), (60, 56), (77, 54), (92, 56)], 'tanks': [(36, 46), (45, 49), (67, 34), (93, 33), (100, 34), (34, 52), (56, 54), (78, 52), (96, 52)]},
        "safe_zones": [{'rect': (44, 72, 24, 8)}],
    },
    "river_bridge_mega": {
        "title": 'MEGA: Cầu Huyết Mạch',
        "briefing": 'Con sông lớn (112x84) với 3 cây cầu bắc ngang. Một chiến trường hoàn hảo cho xe tăng và bộ binh.',
        "rows": [
            "################################################################################################################",
            "#........................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.g###g..................................#",
            "#.............g#g##.......................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgg##g.....g#g#g........................#",
            "#.............###gg........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww#gg#.....##gg#........................#",
            "#.............gg#gg.........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###.....#gg#g........................#",
            "#.............#####..........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwgg.....#g#g#........................#",
            "#.............#####...........................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww......#gggg........................#",
            "#..............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................ggg#g...........#",
            "#...............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................#gg#g...........#",
            "#...............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................g##g#...........#",
            "#................................................wwwwwww.wwwwwwwwwwwwwwwwwwwwww................#g#gg...........#",
            "#.............................................###wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............g##ggg#...........#",
            "#.............................................###gwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............g#g#g.............#",
            "#.............................................g##gwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............######............#",
            "#.............................................g#ggwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............g###g#............#",
            "#.............................................##g#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............#g#g#g............#",
            "#.................................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............###g#............#",
            "#................g###g........#g##g..............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.............##g#g............#",
            "#................#g###........gg##g..............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..............................#",
            "#................#g#g#........gg##g..............rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..............................#",
            "#................##g#g........#####........##g#g.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..#g##..............#g###.....#",
            "#................g##g#g###....#g#gg..g#g#g.#####.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.##g##..............g#g##.....#",
            "#....................#####...........gg###.#g#gg.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.##g##......##g##...gg##g.....#",
            "#........#gggg.......gggg#.......###gg##g#.g####wrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.g#g#g......g#g##...####g.....#",
            "#........###g#.......##gg#.......#####g###.##g#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....#g#gg......g####...####g.....#",
            "#........g#gg#.......g#g##.......#####g#g#g#..wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................#g####............#",
            "#gg#.....g##gg...................gg##g.##gg#..wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................gg#ggg............#",
            "####.....#####.............g#g#g.#g###.g#gg#.wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...................#g#g#ggg#........#",
            "###g.......................gg#g#.......#g#g#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww....................#ggg#g##g........#",
            "##g#.......................#####.......###gwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.....................#g###ggg#........#",
            "#g###g.....................g#g##..........wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..............g#g#g#.....##g#g#........#",
            "#####g.....................g##g#.........wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...............ggggg#.....g#g#g#........#",
            "####gg....g#gg#...g#g#g.................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww................#g#g#g...................#",
            "#ggggg....ggg##...ggg##................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................#g#g##...................#",
            "#g####....#####...g###g...............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................ggg###...................#",
            "#.........gg#g#...#g###..............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................#",
            "#.........g##g#...####g.............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............................................#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrw..............................................#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....................................g####.....#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....................................g#ggg.....#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....................................##ggg.....#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....................................g#g#g.....#",
            "#...............................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.....................................g##g#.....#",
            "#gg............................wrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr...............................................#",
            "###............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................................................#",
            "##g............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...g##g#..........................................#",
            "##g............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...ggg##.........#g##g............................#",
            "###...................##g#g....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...###gg.........#gg#g............................#",
            "#.....................g#g##....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...g###g.........##g##......................g###g.#",
            "#.....................#g###....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...####g.....#g#gg#g##........#gg##.........#g###.#",
            "#.....................g#g#g....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............#g#ggg###........#.#gg.........#g#g#.#",
            "#.....................gg###....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............g##g#............#####.........##ggg.#",
            "#...............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............g#ggg............#gg#g.........g#g##.#",
            "#...............................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............g##g#............###gg...............#",
            "#................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww................................................#",
            "#................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.............................................gg##",
            "#.................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................................g#g#",
            "#..................................wwrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.......................................####",
            "#...................................wrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........................#g##g........gg##",
            "#....................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........................#####........####",
            "#....................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........................##gg#...........#",
            "#....................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..........................###g#.......#g#g#",
            "#....................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrw................#g##g....###g#.......g####",
            "#....................................rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrww...............g#g#g................g####",
            "#....SSSSSSSSSSDDDDDSSSSSSSSSS............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............ggg##gg................g#gg#",
            "#....S.......................S.............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...........#gg###g................g#gg#",
            "#....S.......................S..............wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..........ggg#ggg....................#",
            "#....S.......................S........#gg##..wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.........ggggg#g##g.................#",
            "#....S.......................S........##g#g..wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.........g###ggg#gg.................#",
            "#....S.....M...........A.....S........#g#gg...wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwg###g........##g##.................#",
            "#....S.......................S........#gg#g....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww####........##g#g.................#",
            "#.#ggS.......................S........##gg#.....wwwwwwwwwwwwwwwwwwwwwwwwwwwwww###........###g#.................#",
            "#.#g#S.......................S..................wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwg##..............................#",
            "#.##gS.......................S...................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww##..............................#",
            "#.#g#S.......................S...................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww.................gg###..........#",
            "#.#g#S.......................S................#g##wwwwwwwwwwwwwwwwwwwwwwwwwwwwww................##ggg.......g#g#",
            "#....S.......................S................#g#gwwwwwwwwwwwwwwwwwwwwwwwwwwwwww................##g##.......gg##",
            "#....S.......................S................g###wwwwwwwwwwwwwwwwwwwwwwwwwwwwww................###g#.......####",
            "#....SSSSSSSSSSSSSSSSSSSSSSSSS................ggg#wwwwwwwwwwwwwwwwwwwwwwwwwwwwww................g####.......####",
            "###g#.........................................####wwwwwwwwwwwwwwwwwwwwwwwwwwwwww............................g#g#",
            "###gg.............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww...............................#",
            "###g#.............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................g#ggg........#",
            "##g#g.............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................g##gg........#",
            "#gg##.............................................wwwwwwwwwwwwwwwwwwwwwwwwwwwwww..................g##g#........#",
        ],
        "spawns": {'player': (15, 72), 'enemies': [(72, 17), (82, 16), (92, 16), (102, 16), (72, 23), (81, 24), (92, 24), (102, 25), (70, 34), (80, 34), (90, 35), (100, 34), (72, 44), (82, 44), (92, 44), (102, 44), (74, 56), (84, 56), (94, 56), (104, 56), (78, 68), (88, 68), (98, 68), (106, 68)], 'tanks': [(78, 20), (94, 20), (101, 30), (84, 40), (98, 46), (90, 58), (104, 64)]},
        "safe_zones": [{'rect': (5, 64, 25, 15)}],
    },
    "armored_front_mega": {
        "title": 'MEGA: Tuyến Đầu Bọc Thép',
        "briefing": 'Siêu chiến trường (168x104) dành riêng cho xe tăng bọc thép. Các khu nhà quy hoạch dạng ô cờ.',
        "rows": [
            "########################################################################################################################################################################",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrr#############..#rrrrrrrr####..#######.##rrrrrrrr####.###.#######rrrrrrrr##.#############rrrrrrrr.#####.###.#####rrrrrrrr#######..###.###rrrrrrrr##########.#.#",
            "#rrrrrrrrr################rrrrrrrr###############.rrrrrrrr###########.####rrrrrrrr##########.#.#.#rrrrrrrr.########.#####.rrrrrrrr######.##.######rrrrrrrr#####.######.#",
            "#rrrrrrrrr###############.rrrrrrrr.#.#############rrrrrrrr.#.##.#####.####rrrrrrrr####.#####.#####rrrrrrrr############.###rrrrrrrr################rrrrrrrr##############",
            "#rrrrrrrrr################rrrrrrrr##########.#####rrrrrrrr################rrrrrrrr.###############rrrrrrrr.##.##..########rrrrrrrr################rrrrrrrr##############",
            "#rrrrrrrrr#######.#####.##rrrrrrrr###.############rrrrrrrr#########.######rrrrrrrr#######.########rrrrrrrr################rrrrrrrr##########.#####rrrrrrrr##.###..######",
            "#rrrrrrrrr################rrrrrrrr##.#.###.#######rrrrrrrr################rrrrrrrr#########.#.####rrrrrrrr############.###rrrrrrrr################rrrrrrrr#########.####",
            "#rrrrrrrrr.###############rrrrrrrr############.###rrrrrrrr################rrrrrrrr####.###.###.###rrrrrrrr#####.####..####rrrrrrrr#############.##rrrrrrrr##############",
            "#rrrrrrrrr###########.####rrrrrrrr##.########.####rrrrrrrr#########.######rrrrrrrr###########.####rrrrrrrr########.#######rrrrrrrr#..###.#####.###rrrrrrrr##############",
            "#rrrrrrrrr#############.##rrrrrrrr###############.rrrrrrrr.####..##.####.#rrrrrrrr################rrrrrrrr.##..###########rrrrrrrr###.############rrrrrrrr#######.#.####",
            "#rrrrrrrrr################rrrrrrrr################rrrrrrrr################rrrrrrrr######.#########rrrrrrrr#########.######rrrrrrrr.#######.#.####.rrrrrrrr###.#####.####",
            "#rrrrrrrrr##############.#rrrrrrrr################rrrrrrrr######.#######.#rrrrrrrr##.########.##.#rrrrrrrr##.#############rrrrrrrr#####.##.#######rrrrrrrr####.#########",
            "#rrrrrrrrr######.##.##.###rrrrrrrr############.###rrrrrrrr.#######.#.#####rrrrrrrr###.############rrrrrrrr####.##.########rrrrrrrr##.######.######rrrrrrrr###.########.#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrr################rrrrrrrr.###############rrrrrrrr####.#.########.rrrrrrrr##########.#####rrrrrrrr..##########.###rrrrrrrr################rrrrrrrr##############",
            "#rrrrrrrrr######.#.#######rrrrrrrr#############.##rrrrrrrr####.######.####rrrrrrrr################rrrrrrrr##########..####rrrrrrrr####.######.##.#rrrrrrrr##############",
            "#rrrrrrrrr.####.##########rrrrrrrr###.##.########.rrrrrrrr################rrrrrrrr##.#.#######.###rrrrrrrr#####.##########rrrrrrrr############..##rrrrrrrr############.#",
            "#rrrrrrrrr######.#########rrrrrrrr#############.##rrrrrrrr#####.###.#####.rrrrrrrr############.###rrrrrrrr######.#########rrrrrrrr#.##########.###rrrrrrrr##############",
            "#rrrrrrrrr########.#.#.###rrrrrrrr###.############rrrrrrrr####.###.##..###rrrrrrrr################rrrrrrrr####.#####.#####rrrrrrrr################rrrrrrrr##############",
            "#rrrrrrrrr####.####.###.##rrrrrrrr#.###########.##rrrrrrrr.####.###..####.rrrrrrrr.###############rrrrrrrr###########.####rrrrrrrr##.#####..######rrrrrrrr##.###########",
            "#rrrrrrrrr############.#.#rrrrrrrr###.############rrrrrrrr################rrrrrrrr########.#######rrrrrrrr########.#######rrrrrrrr#####.#.##.#####rrrrrrrr##############",
            "#rrrrrrrrr###########.###.rrrrrrrr################rrrrrrrr###.############rrrrrrrr################rrrrrrrr####.######.###.rrrrrrrr.#######.#####.#rrrrrrrr##########.###",
            "#rrrrrrrrr################rrrrrrrr#.########.####.rrrrrrrr################rrrrrrrr########.###.###rrrrrrrr################rrrrrrrr##.########.####rrrrrrrr#.########.###",
            "#rrrrrrrrr#####.########.#rrrrrrrr##.#############rrrrrrrr.###############rrrrrrrr#######.#.######rrrrrrrr.#####.#.#######rrrrrrrr.###############rrrrrrrr##############",
            "#rrrrrrrrr#############.##rrrrrrrr######..########rrrrrrrr##.####.###.####rrrrrrrr#.##############rrrrrrrr###########.####rrrrrrrr################rrrrrrrr#####.#..#####",
            "#rrrrrrrrr################rrrrrrrr################rrrrrrrr################rrrrrrrr.###.###########rrrrrrrr###..##########.rrrrrrrr######.#########rrrrrrrr##############",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrr################rrrrrrrr#.########.###.#rrrrrrrr#####.######.###rrrrrrrr################rrrrrrrr################rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#.#####..#####",
            "#rrrrrrrrr###########.###.rrrrrrrr###########.####rrrrrrrr##.#############rrrrrrrr#########.######rrrrrrrr################rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#.###.########",
            "#rrrrrrrrr################rrrrrrrr################rrrrrrrr.###############rrrrrrrr################rrrrrrrr################rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##############",
            "#rrrrrrrrr#########.######rrrrrrrr######.##.##.###rrrrrrrr##.############.rrrrrrrr#############.##rrrrrrrr#######...#####.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##############",
            "#rrrrrrrrr##########.#####rrrrrrrr##############.#rrrrrrrr################rrrrrrrr################rrrrrrrr#.###.##.#######rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##.###.###..##",
            "#rrrrrrrrr##.###########.#rrrrrrrr.#####.#########rrrrrrrr#.########.####.rrrrrrrr############.###rrrrrrrr#####.#.########rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr######.#######",
            "#rrrrrrrrr################rrrrrrrr################rrrrrrrr####.##########.rrrrrrrr################rrrrrrrr.########.###.##rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##############",
            "#rrrrrrrrr##.######.######rrrrrrrr################rrrrrrrr###.######..####rrrrrrrr#########..##.##rrrrrrrr#.###.#######.#.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##############",
            "#rrrrrrrrr############.###rrrrrrrr###.#####.#####.rrrrrrrr.############.##rrrrrrrr.#####.#######.#rrrrrrrr##########..####rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr##.###########",
            "#rrrrrrrrr#.#######.######rrrrrrrr##########.#.###rrrrrrrr################rrrrrrrr################rrrrrrrr#####.#.####.###rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.########.####",
            "#rrrrrrrrr#######.##.###.#rrrrrrrr##.#############rrrrrrrr################rrrrrrrr#####..##..#.###rrrrrrrr.#.#########.###rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr###.##########",
            "#rrrrrrrrr################rrrrrrrr#########..#..##rrrrrrrr#####.##.#######rrrrrrrr###########.####rrrrrrrr#.#############.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#.############",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrr################rrrrrrrr###########.####rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr####.###########rrrrrrrr################rrrrrrrr#########.######rrrrrrrr#####.###.####",
            "#rrrrrrrrr################rrrrrrrr#######.##.####.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr###.#.###.#####.rrrrrrrr#####.########.#rrrrrrrr####.#######.###rrrrrrrr#..####.######",
            "#rrrrrrrrr####.#######.###rrrrrrrr##.########.####rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..#.#####.######rrrrrrrr.##.############rrrrrrrr###.############rrrrrrrr##############",
            "#rrrrrrrrr################rrrrrrrr####.######..###rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#####.##########rrrrrrrr###########..###rrrrrrrr###########.####rrrrrrrr###########.##",
            "#rrrrrrrrr######.#########rrrrrrrr##.#############rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr################rrrrrrrr#.######.#######rrrrrrrr########.#.#####rrrrrrrr#####.######.#",
            "#rrrrrrrrr#############.#.rrrrrrrr####.#.#########rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr################rrrrrrrr##.######.######rrrrrrrr##########.#####rrrrrrrr.##.#..#######",
            "#rrrrrrrrr######.##.#####.rrrrrrrr######.#########rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#########.######rrrrrrrr####.###########rrrrrrrr##########..###.rrrrrrrr#####.########",
            "#rrrrrrrrr.##.####.#######rrrrrrrr################rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#..##.#####.#.##rrrrrrrr#######.########rrrrrrrr######.#########rrrrrrrr###.#.######.#",
            "#rrrrrrrrr.######.########rrrrrrrr.#.#############rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr########.##.##.#rrrrrrrr##.###########.#rrrrrrrr########.#######rrrrrrrr##############",
            "#rrrrrrrrr######..########rrrrrrrr####..#.#####.##rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr############..##rrrrrrrr.###############rrrrrrrr.###############rrrrrrrr##.###.#######",
            "#rrrrrrrrr################rrrrrrrr#######.########rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.#######.#######rrrrrrrr####.#.#####.###rrrrrrrr###.######..####rrrrrrrr##############",
            "#rrrrrrrrr#############.##rrrrrrrr..##########.###rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr############.###rrrrrrrr#####.####.#####rrrrrrrr###.#########.##rrrrrrrr###..#########",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSSSSSSSSSDDDDDDDDSSSSSSSSSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS.......M.............A......Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrS............................Srrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "#rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr#",
            "########################################################################################################################################################################",
        ],
        "spawns": {'player': (84, 92), 'enemies': [(30, 14), (50, 14), (66, 10), (81, 14), (102, 14), (122, 14), (138, 10), (24, 24), (42, 24), (60, 24), (78, 24), (96, 24), (114, 24), (132, 24), (150, 24), (30, 36), (49, 36), (66, 40), (81, 36), (102, 36), (122, 36), (138, 40), (33, 50), (54, 50), (74, 50), (98, 50), (114, 45), (132, 50), (148, 50), (84, 60)], 'tanks': [(28, 18), (52, 18), (76, 18), (100, 18), (124, 18), (148, 18), (33, 34), (64, 40), (98, 34), (122, 34), (148, 34), (81, 52)]},
        "safe_zones": [{'rect': (69, 84, 30, 15)}],
    },

}

DEFAULT_MAP_ID = "jungle_outpost"
