MAPS = {
    "jungle_outpost": {
        "title": "Forward Safehouse",
        "briefing": "Gear up inside the secured perimeter, then breach the jungle outpost.",
        "rows": [
            "############################",
            "#..SSSSSSS..t....rrrr...w..#",
            "#..S.....S..t....r..r...w..#",
            "#..S..M..S.ttt...r..r...w..#",
            "#..S..A..Srrrr...r..rrrrw..#",
            "#..S.....S.......r.........#",
            "#..SSSDSSS..####.r..####...#",
            "#....r......####....####...#",
            "#....r......####....####...#",
            "#..rrrrrr...####....####...#",
            "#..r.......................#",
            "#..r..tttt....rrrrrrrr.....#",
            "#..r....t.....r............#",
            "#..r.####.....r....####....#",
            "#..r.####...ttt....####....#",
            "#..r.####.....r....####....#",
            "#..r..........rrrr.........#",
            "#..r..www....r.C.r..ggg....#",
            "#.....www....rrrrr..ggg....#",
            "#..........................#",
            "############################",
        ],
        "spawns": {
            "player": (5, 4),
            "enemies": [(20, 3), (22, 10), (17, 14), (12, 10), (10, 18)],
            "tanks": [(23, 16), (6, 12)],
        },
        "items": {
            "medkit": [(5, 3), (8, 19)],
            "grenade": [(6, 4), (14, 11)],
            "ammo": [(4, 5), (11, 9)],
        },
        "safe_zones": [
            {"name": "forward_safehouse", "rect": (3, 1, 7, 6)},
        ],
        "doors": [(6, 6)],
    },
    "trench_line": {
        "title": "Trench Line",
        "briefing": "Push through the trench network before taking the bunker.",
        "rows": [
            "############################",
            "#........rrrrrr............#",
            "#..tttt..r....r..tttttt....#",
            "#..t..t..r....r..t....t....#",
            "#..t..t..rrrrrr..t....t....#",
            "#..t..t..........t....t....#",
            "#..t..tttttttttttt....t....#",
            "#..t..................t....#",
            "#..tttttt..####..tttttt....#",
            "#..........#..#............#",
            "#..rrrrrr...CC...rrrrrr....#",
            "#..r.......####.......r....#",
            "#..r..wwww......wwww..r....#",
            "#..r..wwww......wwww..r....#",
            "#..rrrrrr..tttt..rrrrrr....#",
            "#..........................#",
            "#..gggg............gggg....#",
            "#..gggg....tttt....gggg....#",
            "#..........................#",
            "#............rrrr..........#",
            "############################",
        ],
        "spawns": {
            "player": (3, 18),
            "enemies": [(18, 3), (21, 5), (18, 16), (7, 7), (12, 15), (23, 18)],
            "tanks": [(20, 10), (10, 3)],
        },
        "items": {
            "medkit": [(5, 18), (15, 15)],
            "grenade": [(8, 7), (20, 17)],
            "ammo": [(11, 18), (16, 2)],
        },
    },
    "river_bridge": {
        "title": "River Bridge",
        "briefing": "Cross the bridge, destroy armor, and secure the far side.",
        "rows": [
            "############################",
            "#.....ggg............ggg...#",
            "#.....ggg....tttt....ggg...#",
            "#............t..t..........#",
            "#..rrrrrrrrrrt..trrrrrrr...#",
            "#..r...................r...#",
            "#..r..wwwwwwwwwwwwww...r...#",
            "#..r..wwwwwwwwwwwwww...r...#",
            "#..rrrrrrrrrrrrrrrrrrrrr...#",
            "#.....wwwwwwwwwwwwww.......#",
            "#.....wwwwwwwwwwwwww.......#",
            "#..rrrrrrrrrrrrrrrrrrrrr...#",
            "#..r...................r...#",
            "#..r...####......####..r...#",
            "#..r...####..CC..####..r...#",
            "#..r...####......####..r...#",
            "#..rrrrrrrr..tt..rrrrrrr...#",
            "#............tt............#",
            "#..ggg................ggg..#",
            "#..........................#",
            "############################",
        ],
        "spawns": {
            "player": (3, 19),
            "enemies": [(21, 3), (22, 12), (16, 15), (12, 4), (7, 16)],
            "tanks": [(22, 14), (10, 8), (17, 8)],
        },
        "items": {
            "medkit": [(5, 18), (20, 12)],
            "grenade": [(9, 16), (16, 13)],
            "ammo": [(6, 5), (23, 3)],
        },
    },
    "armored_front": {
        "title": "Armored Front",
        "briefing": "Advance from the rear safe zone, break the armored roadblock, and seize the rail depot.",
        "rows": [
            "##########################################",
            "#..SSSSSSSSS....ggg.....rrrrrr.....wwwww.#",
            "#..S.......S....ggg.....r....r.....wwwww.#",
            "#..S..M.A..S............r.tt.r...........#",
            "#..S.......S..rrrrrrrrrrrrtt.rrrrrrrr....#",
            "#..SSSDDSSSS..r.......ttt....t.....r.....#",
            "#......r......r..####..t..####....r......#",
            "#......r..ttt.r..####.....####....r.gg...#",
            "#..rrrrrrrrr..r..####..C..####..rrrrgg...#",
            "#..r......t...r..####.....####..r........#",
            "#..r..www.t...rrrrrrrrrrrrrrrrrrr..ttt...#",
            "#..r..www.t.........wwwwww.......r..t....#",
            "#..r..wwwwwww.......wwwwww.......r..t....#",
            "#..rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr..t....#",
            "#...........t..####....tt....####........#",
            "#..gggg.....t..####....tt....####..ggg...#",
            "#..gggg..rrrr..####..rrrrrr..####..ggg...#",
            "#........r..r........r....r..............#",
            "#..tttt..r..rrrrrrrrrr....rrrrrr..ttt....#",
            "#..t.....r.......tt.........t..r..t......#",
            "#..t.....rrrrrr..tt..rrrrrrrr..r..t......#",
            "#..tttt.........wwwwww.........r..ttt....#",
            "#........rrrrrrrwwwwwwrrrrrrrrrr.........#",
            "#..ggg...r....................r...ggg....#",
            "#........rrrrrrrrrrrrrrrrrrrrrr..........#",
            "##########################################",
        ],
        "spawns": {
            "player": (6, 4),
            "enemies": [(25, 3), (31, 7), (20, 10), (33, 12), (16, 17), (27, 18), (35, 20), (12, 23)],
            "tanks": [(30, 4), (23, 13), (34, 16), (15, 20), (24, 23)],
            "aircraft_enemies": [
                {
                    "id": "bomber_north_run",
                    "unit": "bomber",
                    "entry": (8, -2),
                    "exit": (35, 27),
                    "target": (23, 8),
                    "delay": 18.0,
                    "cooldown": 42.0,
                },
                {
                    "id": "bomber_river_run",
                    "unit": "bomber",
                    "entry": (43, 6),
                    "exit": (-3, 21),
                    "target": (25, 13),
                    "delay": 34.0,
                    "cooldown": 55.0,
                },
            ],
        },
        "safe_zones": [
            {"name": "western_depot", "rect": (2, 1, 11, 6)},
        ],
        "doors": [(6, 5), (7, 5)],
        "capture_points": [
            {"id": "rail_depot", "tile": (24, 8), "radius": 2},
        ],
        "items": {
            "medkit": [(5, 3), (9, 22), (17, 17), (34, 23)],
            "grenade": [(7, 4), (14, 9), (29, 17), (36, 17)],
            "ammo": [(8, 3), (12, 13), (21, 20), (31, 6), (37, 24)],
        },
        "boss_wave": {
            "trigger_radius_tile": (24, 8),
            "boss_spawn": (36, 8),
            "boss_kind": "super_heavy",
            "adds_spawns": [(34, 4), (34, 12), (37, 10), (37, 6)],
        },
    },
}

DEFAULT_MAP_ID = "jungle_outpost"
